Update BG5300.baf
I had this problem during the installation: 
[NTotSC/BAF/Area/BG5300.BAF]  ERROR at line 11 column 1-0
Near Text: 
	Failure("lexing: empty token")
ERROR: parsing [NTotSC/BAF/Area/BG5300.BAF]: Failure("lexing: empty token")
Stopping installation because of error.

It seems that removing the '+'   at the lines 11, 15 , 20 and 23 fix the error.